In [1]:
import torch
from torchvision import (
    datasets,
    transforms
)
from torch.utils import data

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("seaborn-v0_8")
plt.rcParams["font.family"] = "monospace"

In [2]:
if torch.cuda.is_available():
    print("CUDA found, bounding...")
    DEVICE = torch.device('cuda:0')
else:
    print("NO CUDA found, bounding to CPU...")
    DEVICE = torch.device('cpu')

CUDA found, bounding...


In [3]:
DTYPE = torch.float32

In [42]:
# Jacobian Matrix
X = torch.tensor([1., 2.], dtype=DTYPE, device=DEVICE, requires_grad=True)
X

tensor([1., 2.], device='cuda:0', requires_grad=True)

In [43]:
y = X ** 2
y

tensor([1., 4.], device='cuda:0', grad_fn=<PowBackward0>)

In [44]:
y.sum().backward()      # y.sum() -> Scalar
X.grad

tensor([2., 4.], device='cuda:0')

In [45]:
X.grad.zero_()
y = X ** 2

U = y.detach()
# U = y
Z = U * X

In [46]:
y, Z

(tensor([1., 4.], device='cuda:0', grad_fn=<PowBackward0>),
 tensor([1., 8.], device='cuda:0', grad_fn=<MulBackward0>))

In [47]:
Z.sum().backward()
X.grad

tensor([1., 4.], device='cuda:0')