In [1]:
import torch
from torchvision import (
    datasets,
    transforms
)
from torch.utils import data

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("seaborn-v0_8")
plt.rcParams["font.family"] = "monospace"

In [2]:
if torch.cuda.is_available():
    print("CUDA found, bounding...")
    DEVICE = torch.device('cuda:0')
else:
    print("NO CUDA found, bounding to CPU...")
    DEVICE = torch.device('cpu')

CUDA found, bounding...


In [3]:
DTYPE = torch.float32

In [7]:
X = torch.arange(0, 5, dtype=DTYPE, device=DEVICE, requires_grad=True)
X

tensor([0., 1., 2., 3., 4.], device='cuda:0', requires_grad=True)

In [14]:
y = sum(2 * X + X ** 2)
y

tensor(50., device='cuda:0', grad_fn=<AddBackward0>)

In [15]:
y.backward()

In [16]:
X.grad

tensor([ 2.,  4.,  6.,  8., 10.], device='cuda:0')

In [17]:
# y = 2X + X^2
# y' -> 2 + 2X
Xn = 2 * X + 2
Xn

tensor([ 2.,  4.,  6.,  8., 10.], device='cuda:0', grad_fn=<AddBackward0>)

In [20]:
Xn.all() == X.grad.all()

tensor(True, device='cuda:0')